name: Workflow to apply the plan
on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Terraform command to run'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    name: Applying the plan
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    env:
      NEWRELIC_API_KEY: ${{ secrets.NEWRELIC_API_KEY }} # Setting environment variable at the job level

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        id: init
        run: terraform init -upgrade

      - name: Terraform Plan
        run: terraform plan -var="newrelic_api_key=${{ env.NEWRELIC_API_KEY }}"

      - name: Run Terraform Command
        run: terraform ${{ github.event.inputs.command }} -auto-approve -var="newrelic_api_key=${{ env.NEWRELIC_API_KEY }}"
